#!/bin/bash

# Deterministic tar creation referencing
# https://www.gnu.org/software/tar/manual/tar.html#Reproducibility
deterministic_tar() {
  local ARCHIVE_NAME="$1"
  local SOURCE_DIR="$2"

  # Fixed timestamp rather than version controlled
  FIXED_TIMESTAMP="2024-01-01T00:00:00Z"

  tar -cf - "${SOURCE_DIR}" | gzip  > "${ARCHIVE_NAME}"
}
