name: MySQL client binaries lightweight packages
on:
  workflow_dispatch:
  push:
    branches:
      - mysql

jobs:
  mysql-client-macos11:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.27, 8.0.28]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} binary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        id: build
        run: |
          curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
          tar xzf mysql-client.tar.gz
          pushd mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
          GZIP=-n tar --sort=name --mtime='2020-01-01 00:00:00' -czf ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}

      - name: Verify Deterministic Build
        uses: ./.github/workflows/verify-deterministic.yml
        with:
          artifact_name: ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz
          build_command: |
            curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
            tar xzf mysql-client.tar.gz
            pushd mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
            GZIP=-n tar --sort=name --mtime='2020-01-01 00:00:00' -czf ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos11-${{ matrix.arch }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: mysql-client
          allowUpdates: true
          artifacts: ${{ matrix.binary }}-${{ matrix.version }}-macos11-${{ matrix.arch }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

  mysql-client-macos14:
    strategy:
      matrix:
        binary: [mysql, mysqladmin]
        arch: [x86_64, arm64]
        version: [8.0.36]
    name: Make a lightweight package for the ${{ matrix.arch }} ${{ matrix.binary }} binary v${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Package
        id: build
        run: |
          curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
          tar xzf mysql-client.tar.gz
          pushd mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
          GZIP=-n tar --sort=name --mtime='2020-01-01 00:00:00' -czf ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}

      - name: Verify Deterministic Build
        uses: ./.github/workflows/verify-deterministic.yml
        with:
          artifact_name: ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz
          build_command: |
            curl -SsfL "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz" -o mysql-client.tar.gz
            tar xzf mysql-client.tar.gz
            pushd mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}/bin/ && (ls -1 | grep -v '^${{ matrix.binary }}$' | xargs rm) && popd
            GZIP=-n tar --sort=name --mtime='2020-01-01 00:00:00' -czf ${{ matrix.binary }}-${{ matrix.version }}-macos14-${{ matrix.arch }}.tar.gz mysql-${{ matrix.version }}-macos14-${{ matrix.arch }}